#:schema node_modules/wrangler/config-schema.json
name = "ppr-pages"
pages_build_output_dir = "./.next/assets"
compatibility_date = "2024-10-05"

[[services]]
binding = "BACKEND"
service = "next-ppr"
